server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopverse
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379